Repository fusionjs/fusion-plugin-universal-events, pull requests merged in 2018-11, with the labels that each got.

#163 Release v1.2.1
  package.json
Labels: release

#164 Export types
  src/index.js
Labels: bugfix

#166 Release v1.3.0
  package.json
Labels: release

#167 Upgrade dependencies
  package.json
  src/storage/index.js
  yarn.lock
Labels: greenkeeping
