Repository fusionjs/fusion-plugin-universal-events, pull requests merged in 2018-10, with the labels that each got.

#151 Release v1.2.0
  package.json
Labels: release

#153 Upgrade dependency versions
  README.md
  package.json
  yarn.lock
Labels: greenkeeping

#159 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor
