Repository fusionjs/fusion-plugin-universal-events, pull requests merged in 2019-03, with the labels that each got.

#185 Fix issue in documentation where 'this' would be bound incorrectly
  README.md
Labels: bugfix, docs

#186 Release v1.3.3-0
  package.json
Labels: release

#187 Release v1.3.3
  package.json
Labels: release

#188 Update error handling logic
  src/__tests__/test.node.js
  src/server.js
Labels: bugfix
