Repository fusionjs/fusion-plugin-universal-events, pull requests merged in 2019-01, with the labels that each got.

#158 Use visibility API instead of beforeunload
  README.md
  src/__tests__/test.browser.js
  src/browser.js
Labels: bugfix, refactor

#171 Release v1.3.1-0
  package.json
Labels: release

#174 Release v1.3.1-1
  package.json
Labels: release

#175 Release v1.3.1
  package.json
Labels: release

#177 Fix issue with event flushing
  src/__tests__/test.browser.js
  src/browser.js
Labels: bugfix

#178 Release v1.3.2
  package.json
Labels: release
